---
- name: create a new Windows VM
  amazon.aws.ec2_instance:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ windows_vm_name }}"
    instance_type: t3.medium
    region: "{{ region }}"
    image_id: "{{ ami_win }}"
    key_name: aws_windows2019_20220415
    #key_name: "{{ key }}"
    state: running
    wait: true
    termination_protection: false
    #vpc_subnet_id: "{{ item.subnet_id }}"
    #network:
    #  assign_public_ip: false
    security_group: "{{ win_security_group }}"
    user_data: "{{ lookup('file', 'files/init.ps1') }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 30
          volume_type: gp2
          delete_on_termination: true
    tags:
      Name: "{{ owner }} Kerberos Windows 2019"
      Owner: "{{ owner }}"